<a href="https://colab.research.google.com/github/ompatel420/ML-Practicals/blob/main/ML_P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
dataset =pd.read_csv('/content/drive/MyDrive/ML/Dataset/zoo.csv')
dataset

      animal  uniq_id  water_need
0   elephant     1001         500
1   elephant     1002         600
2   elephant     1003         550
3      tiger     1004         300
4      tiger     1005         320
5      tiger     1006         330
6      tiger     1007         290
7      tiger     1008         310
8      zebra     1009         200
9      zebra     1010         220
10     zebra     1011         240
11     zebra     1012         230
12     zebra     1013         220
13     zebra     1014         100
14     zebra     1015          80
15      lion     1016         420
16      lion     1017         600
17      lion     1018         500
18      lion     1019         390
19  kangaroo     1020         410
20  kangaroo     1021         430
21  kangaroo     1022         410

In [ ]:
outside_data = pd.DataFrame({
    'animal': ['giraffe', 'giraffe', 'hippo', 'lion'],
    'uniq_id': [1023, 1024, 1025,999],
    'water_need': [700, 750, 800,123]
})
display(outside_data.head())

    animal  uniq_id  water_need
0  giraffe     1023         700
1  giraffe     1024         750
2    hippo     1025         800
3     lion      999         123

In [ ]:
combined_dataset = pd.concat([dataset, outside_data], ignore_index=True)
display(combined_dataset)

      animal  uniq_id  water_need
0   elephant     1001         500
1   elephant     1002         600
2   elephant     1003         550
3      tiger     1004         300
4      tiger     1005         320
5      tiger     1006         330
6      tiger     1007         290
7      tiger     1008         310
8      zebra     1009         200
9      zebra     1010         220
10     zebra     1011         240
11     zebra     1012         230
12     zebra     1013         220
13     zebra     1014         100
14     zebra     1015          80
15      lion     1016         420
16      lion     1017         600
17      lion     1018         500
18      lion     1019         390
19  kangaroo     1020         410
20  kangaroo     1021         430
21  kangaroo     1022         410
22   giraffe     1023         700
23   giraffe     1024         750
24     hippo     1025         800
25      lion      999         123

In [ ]:
dataset.sort_values('water_need')

      animal  uniq_id  water_need
14     zebra     1015          80
13     zebra     1014         100
8      zebra     1009         200
9      zebra     1010         220
12     zebra     1013         220
11     zebra     1012         230
10     zebra     1011         240
6      tiger     1007         290
3      tiger     1004         300
7      tiger     1008         310
4      tiger     1005         320
5      tiger     1006         330
18      lion     1019         390
19  kangaroo     1020         410
21  kangaroo     1022         410
15      lion     1016         420
20  kangaroo     1021         430
17      lion     1018         500
0   elephant     1001         500
2   elephant     1003         550
1   elephant     1002         600
16      lion     1017         600

In [ ]:
merged_dataset_outer = pd.merge(dataset, outside_data, how='outer')
display(merged_dataset_outer)

      animal  uniq_id  water_need
0   elephant     1001         500
1   elephant     1002         600
2   elephant     1003         550
3    giraffe     1023         700
4    giraffe     1024         750
5      hippo     1025         800
6   kangaroo     1020         410
7   kangaroo     1021         430
8   kangaroo     1022         410
9       lion      999         123
10      lion     1016         420
11      lion     1017         600
12      lion     1018         500
13      lion     1019         390
14     tiger     1004         300
15     tiger     1005         320
16     tiger     1006         330
17     tiger     1007         290
18     tiger     1008         310
19     zebra     1009         200
20     zebra     1010         220
21     zebra     1011         240
22     zebra     1012         230
23     zebra     1013         220
24     zebra     1014         100
25     zebra     1015          80

In [ ]:
dataset.sort_values('water_need')

      animal  uniq_id  water_need
14     zebra     1015          80
13     zebra     1014         100
8      zebra     1009         200
9      zebra     1010         220
12     zebra     1013         220
11     zebra     1012         230
10     zebra     1011         240
6      tiger     1007         290
3      tiger     1004         300
7      tiger     1008         310
4      tiger     1005         320
5      tiger     1006         330
18      lion     1019         390
19  kangaroo     1020         410
21  kangaroo     1022         410
15      lion     1016         420
20  kangaroo     1021         430
17      lion     1018         500
0   elephant     1001         500
2   elephant     1003         550
1   elephant     1002         600
16      lion     1017         600

In [ ]:
merged_dataset_inner = pd.merge(dataset, outside_data, how='inner')
display(merged_dataset_inner)

Empty DataFrame
Columns: [animal, uniq_id, water_need]
Index: []

In [ ]:
df4=pd.read_excel("/content/drive/MyDrive/ML/Dataset/Covid cases in India.xlsx")
df4

,S. No.,Name of State / UT,TotalConfirmedCases,Active,Recovered,Deaths
0,1.0,Maharashtra,20228,15649,3800,779
1,2.0,Gujarat,7797,5234,2091,472
2,3.0,Delhi,6542,4454,2020,68
3,4.0,Tamil Nadu,6535,4667,1824,44
4,5.0,Rajasthan,3741,1458,2176,107
5,6.0,Madhya Pradesh,3457,1766,1480,211
6,7.0,Uttar Pradesh,3373,1800,1499,74
7,8.0,Andhra Pradesh,1930,999,887,44
8,9.0,West Bengal,1786,1243,372,171
9,10.0,Punjab,1762,1574,157,31
10,11.0,Telangana,1163,382,751,30
11,12.0,Jammu and Kashmir,836,459,368,9
12,13.0,Karnataka,794,377,386,30
13,14.0,Haryana,675,376,290,9
14,15.0,Bihar,629,306,318,5
15,16.0,Kerala,506,17,485,4
16,17.0,Odisha,352,281,68,3
17,18.0,Chandigarh,169,143,24,2
18,19.0,Jharkhand,156,75,78,3
19,20.0,Tripura,135,133,2,0
20,21.0,Uttarakhand,67,20,46,1
21,22.0,Assam,62,26,35,1
22,23.0,Chhattisgarh,59,16,43,0
23,24.0,Himachal Pradesh,52,11,35,3
24,25.0,Ladakh,42,24,18,0
25,26.0,Andaman and Nicobar Islands,33,0,33,0
26,27.0,Meghalaya,13,2,10,1
27,28.0,Puducherry,10,2,8,0
28,29.0,Goa,7,0,7,0
29,30.0,Manipur,2,0,2,0
30,31.0,Mizoram,1,0,1,0
31,32.0,Arunachal Pradesh,1,0,1,0
32,33.0,Dadra and Nagar Haveli and Daman and Diu,1,1,0,0
33,NaN,Total,62916,41495,19315,2102

In [ ]:
print(type(df4))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
df4.columns

Index(['S. No.', 'Name of State / UT', 'TotalConfirmedCases', 'Active',
       'Recovered', 'Deaths'],
      dtype='object')

In [ ]:
df4.shape

(34, 6)

In [ ]:
df4.sample(2)

    S. No. Name of State / UT  TotalConfirmedCases  Active  Recovered  Deaths
28    29.0                Goa                    7       0          7       0
20    21.0        Uttarakhand                   67      20         46       1